// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf;

/** All Visitor */

public interface AllVisitor<R, A> extends lbnf.Absyn.Grammar.Visitor<R, A>, lbnf.Absyn.Def.Visitor<R, A>,
		lbnf.Absyn.Item.Visitor<R, A>, lbnf.Absyn.Cat.Visitor<R, A>, lbnf.Absyn.Label.Visitor<R, A>,
		lbnf.Absyn.LabelId.Visitor<R, A>, lbnf.Absyn.ProfItem.Visitor<R, A>, lbnf.Absyn.IntList.Visitor<R, A>,
		lbnf.Absyn.RHS.Visitor<R, A>, lbnf.Absyn.MinimumSize.Visitor<R, A>, lbnf.Absyn.Reg.Visitor<R, A> {
}
