// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class Cat implements java.io.Serializable {
	public abstract <R, A> R accept(Cat.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.ListCat p, A arg);

		public R visit(lbnf.Absyn.IdCat p, A arg);

	}

}
