// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class Coercions extends Def {
	public final String ident_;
	public final Integer integer_;

	public Coercions(String p1, Integer p2) {
		ident_ = p1;
		integer_ = p2;
	}

	public <R, A> R accept(lbnf.Absyn.Def.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.Coercions) {
			lbnf.Absyn.Coercions x = (lbnf.Absyn.Coercions) o;
			return this.ident_.equals(x.ident_) && this.integer_.equals(x.integer_);
		}
		return false;
	}

	public int hashCode() {
		return 37 * (this.ident_.hashCode()) + this.integer_.hashCode();
	}

}
