// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class Def implements java.io.Serializable {
	public abstract <R, A> R accept(Def.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.Rule p, A arg);

		public R visit(lbnf.Absyn.Comment p, A arg);

		public R visit(lbnf.Absyn.Comments p, A arg);

		public R visit(lbnf.Absyn.Internal p, A arg);

		public R visit(lbnf.Absyn.Token p, A arg);

		public R visit(lbnf.Absyn.PosToken p, A arg);

		public R visit(lbnf.Absyn.Entryp p, A arg);

		public R visit(lbnf.Absyn.Separator p, A arg);

		public R visit(lbnf.Absyn.Terminator p, A arg);

		public R visit(lbnf.Absyn.Coercions p, A arg);

		public R visit(lbnf.Absyn.Rules p, A arg);

		public R visit(lbnf.Absyn.Layout p, A arg);

		public R visit(lbnf.Absyn.LayoutStop p, A arg);

		public R visit(lbnf.Absyn.LayoutTop p, A arg);

	}

}
