// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class Entryp extends Def {
	public final ListIdent listident_;

	public Entryp(ListIdent p1) {
		listident_ = p1;
	}

	public <R, A> R accept(lbnf.Absyn.Def.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.Entryp) {
			lbnf.Absyn.Entryp x = (lbnf.Absyn.Entryp) o;
			return this.listident_.equals(x.listident_);
		}
		return false;
	}

	public int hashCode() {
		return this.listident_.hashCode();
	}

}
