// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class Grammar implements java.io.Serializable {
	public abstract <R, A> R accept(Grammar.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.MkGrammar p, A arg);

	}

}
