// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class Id extends LabelId {
	public final String ident_;

	public Id(String p1) {
		ident_ = p1;
	}

	public <R, A> R accept(lbnf.Absyn.LabelId.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.Id) {
			lbnf.Absyn.Id x = (lbnf.Absyn.Id) o;
			return this.ident_.equals(x.ident_);
		}
		return false;
	}

	public int hashCode() {
		return this.ident_.hashCode();
	}

}
