// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class Internal extends Def {
	public final Label label_;
	public final Cat cat_;
	public final ListItem listitem_;

	public Internal(Label p1, Cat p2, ListItem p3) {
		label_ = p1;
		cat_ = p2;
		listitem_ = p3;
	}

	public <R, A> R accept(lbnf.Absyn.Def.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.Internal) {
			lbnf.Absyn.Internal x = (lbnf.Absyn.Internal) o;
			return this.label_.equals(x.label_) && this.cat_.equals(x.cat_) && this.listitem_.equals(x.listitem_);
		}
		return false;
	}

	public int hashCode() {
		return 37 * (37 * (this.label_.hashCode()) + this.cat_.hashCode()) + this.listitem_.hashCode();
	}

}
