// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class IntList implements java.io.Serializable {
	public abstract <R, A> R accept(IntList.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.Ints p, A arg);

	}

}
