// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class Ints extends IntList {
	public final ListInteger listinteger_;

	public Ints(ListInteger p1) {
		listinteger_ = p1;
	}

	public <R, A> R accept(lbnf.Absyn.IntList.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.Ints) {
			lbnf.Absyn.Ints x = (lbnf.Absyn.Ints) o;
			return this.listinteger_.equals(x.listinteger_);
		}
		return false;
	}

	public int hashCode() {
		return this.listinteger_.hashCode();
	}

}
