// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class Item implements java.io.Serializable {
	public abstract <R, A> R accept(Item.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.Terminal p, A arg);

		public R visit(lbnf.Absyn.NTerminal p, A arg);

	}

}
