// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class LabelId implements java.io.Serializable {
	public abstract <R, A> R accept(LabelId.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.Id p, A arg);

		public R visit(lbnf.Absyn.Wild p, A arg);

		public R visit(lbnf.Absyn.ListE p, A arg);

		public R visit(lbnf.Absyn.ListCons p, A arg);

		public R visit(lbnf.Absyn.ListOne p, A arg);

	}

}
