// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class Label implements java.io.Serializable {
	public abstract <R, A> R accept(Label.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.LabNoP p, A arg);

		public R visit(lbnf.Absyn.LabP p, A arg);

		public R visit(lbnf.Absyn.LabPF p, A arg);

		public R visit(lbnf.Absyn.LabF p, A arg);

	}

}
