// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class MinimumSize implements java.io.Serializable {
	public abstract <R, A> R accept(MinimumSize.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.MNonempty p, A arg);

		public R visit(lbnf.Absyn.MEmpty p, A arg);

	}

}
