// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class MkGrammar extends Grammar {
	public final ListDef listdef_;

	public MkGrammar(ListDef p1) {
		listdef_ = p1;
	}

	public <R, A> R accept(lbnf.Absyn.Grammar.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.MkGrammar) {
			lbnf.Absyn.MkGrammar x = (lbnf.Absyn.MkGrammar) o;
			return this.listdef_.equals(x.listdef_);
		}
		return false;
	}

	public int hashCode() {
		return this.listdef_.hashCode();
	}

}
