// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class MkRHS extends RHS {
	public final ListItem listitem_;

	public MkRHS(ListItem p1) {
		listitem_ = p1;
	}

	public <R, A> R accept(lbnf.Absyn.RHS.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.MkRHS) {
			lbnf.Absyn.MkRHS x = (lbnf.Absyn.MkRHS) o;
			return this.listitem_.equals(x.listitem_);
		}
		return false;
	}

	public int hashCode() {
		return this.listitem_.hashCode();
	}

}
