// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class PosToken extends Def {
	public final String ident_;
	public final Reg reg_;

	public PosToken(String p1, Reg p2) {
		ident_ = p1;
		reg_ = p2;
	}

	public <R, A> R accept(lbnf.Absyn.Def.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.PosToken) {
			lbnf.Absyn.PosToken x = (lbnf.Absyn.PosToken) o;
			return this.ident_.equals(x.ident_) && this.reg_.equals(x.reg_);
		}
		return false;
	}

	public int hashCode() {
		return 37 * (this.ident_.hashCode()) + this.reg_.hashCode();
	}

}
