// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class RChar extends Reg {
	public final Character char_;

	public RChar(Character p1) {
		char_ = p1;
	}

	public <R, A> R accept(lbnf.Absyn.Reg.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.RChar) {
			lbnf.Absyn.RChar x = (lbnf.Absyn.RChar) o;
			return this.char_.equals(x.char_);
		}
		return false;
	}

	public int hashCode() {
		return this.char_.hashCode();
	}

}
