// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public abstract class Reg implements java.io.Serializable {
	public abstract <R, A> R accept(Reg.Visitor<R, A> v, A arg);

	public interface Visitor<R, A> {
		public R visit(lbnf.Absyn.RSeq p, A arg);

		public R visit(lbnf.Absyn.RAlt p, A arg);

		public R visit(lbnf.Absyn.RMinus p, A arg);

		public R visit(lbnf.Absyn.RStar p, A arg);

		public R visit(lbnf.Absyn.RPlus p, A arg);

		public R visit(lbnf.Absyn.ROpt p, A arg);

		public R visit(lbnf.Absyn.REps p, A arg);

		public R visit(lbnf.Absyn.RChar p, A arg);

		public R visit(lbnf.Absyn.RAlts p, A arg);

		public R visit(lbnf.Absyn.RSeqs p, A arg);

		public R visit(lbnf.Absyn.RDigit p, A arg);

		public R visit(lbnf.Absyn.RLetter p, A arg);

		public R visit(lbnf.Absyn.RUpper p, A arg);

		public R visit(lbnf.Absyn.RLower p, A arg);

		public R visit(lbnf.Absyn.RAny p, A arg);

	}

}
