// File generated by the BNF Converter (bnfc 2.9.5).

package lbnf.Absyn;

public class RSeq extends Reg {
	public final Reg reg_1, reg_2;

	public RSeq(Reg p1, Reg p2) {
		reg_1 = p1;
		reg_2 = p2;
	}

	public <R, A> R accept(lbnf.Absyn.Reg.Visitor<R, A> v, A arg) {
		return v.visit(this, arg);
	}

	public boolean equals(java.lang.Object o) {
		if (this == o)
			return true;
		if (o instanceof lbnf.Absyn.RSeq) {
			lbnf.Absyn.RSeq x = (lbnf.Absyn.RSeq) o;
			return this.reg_1.equals(x.reg_1) && this.reg_2.equals(x.reg_2);
		}
		return false;
	}

	public int hashCode() {
		return 37 * (this.reg_1.hashCode()) + this.reg_2.hashCode();
	}

}
